name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true

      - name: Merge Mochawesome reports
        run: |
          npx mochawesome-merge cypress/reports/*.json > mochawesome.json
          npx marge mochawesome.json --reportDir=cypress/reports/html

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html


        